//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_training
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int training_id { get; set; }
        public System.DateTime completion_date { get; set; }
        public int employee_code { get; set; }
    }
}
